### ISSUE TITLE
Abertura de edital e formulário correspondente de inscrição

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/ppgselecao#14]
**Motivação**

Abertura de editais e o correspondente formulário de inscrição (que pode mudar ao longo dos anos) é o coração desse sistema, vamos manter essa issue aberta até implementarmos todo o workflow de abertura de edital e inscrição, para partirmos assim para as etapas pós inscrição.

**Contexto**
Cada programa de pós-graduação pode ter diferentes períodos de inscrições para seleção de candidatos e apesar de compartilharem muitos itens, cada programa abre seu próprio edital. Há campos no formulário de inscrição que são comuns e obrigatórios a todos programas, mas ouro não, assim deve-se ter a possibilidade de adicionar-se campos customizados. Portanto, a instância do formulários estará relacionada ao programa.

**Etapas de implementação**

- [x] Criação de uma tabela *editais* na qual o secretário vai poder gerenciar novos períodos de inscrições e afins
- [x] Criação da tabela *inscricoes* para formulários de inscrição em si 
- [ ] Criação de tabelas adicionais para o secretário poder adicionar campos dinamicamente no formulário de inscrição (igual webform/field_api do drupal)
- [ ] Criação de templates/Controller para cadastrar editais e formulários de inscrição

**Comment by alecostaweb** [comment]
Podemos seguir com camel case sem underline? Please!

**Comment by alecostaweb** [comment]
Pensei em algo do tipo:
![ppgselecaoModel](https://user-images.githubusercontent.com/10613364/62898243-69ee9e80-bd2b-11e9-8f32-93c424df69c8.png)

**Comment by alecostaweb** [comment]
editais = processos seletivos
inscricoes = candidatos
questionarios = campos a preencher no formulário de inscrição do processo seletivo
campos = detalhamento dos campos 
dados = armazenamento das informações enviadas

**Comment by alecostaweb** [comment]
Fazendo relação com o drupal/webform:
webform = formulário 
webform_component = campos
webform_submissions = envios = inscricoes
webform_submitted_data = dados enviados = dados

**Comment by alecostaweb** [comment]
Estava pensando se a tabela questionário seria necessária, o que acha @thiagogomesverissimo?

**Comment by alecostaweb** [comment]
Aqui já contando com os pagamentos:
![ppgselecaoModelPagamentos](https://user-images.githubusercontent.com/10613364/62900552-cacca580-bd30-11e9-9175-42e9f4dd800f.png)

**Comment by alecostaweb** [comment]
Outra abordagem eliminando a tabela questionario
![ppgselecaoModelPagamentos2](https://user-images.githubusercontent.com/10613364/62941085-9649ff80-bdab-11e9-99ad-db167b863e92.png)

**Comment by masakik** [comment]
acho que a tabela campos deveria ser ligado aos editais pois são as questoes a serem respondidas

**Comment by alecostaweb** [comment]
Vou compartilhar via google drive o arquivo do mysql workbench

**Comment by masakik** [comment]
talvez a idéia de questionário não seja ruim pois um conjunto de questões fica ligado ao questionário. Assim cada edital poderia ter mais de um questionário.

**Comment by alecostaweb** [comment]
Compartilhei o diagrama em link enviado via telegram

**Comment by alecostaweb** [comment]
Depois de nossa conversa:

Pós:
1. Loga
2. Cadastra um processo
3. Cadastra um questionário e os campos do questionário

Candidado:
1. Cadidato visualiza os processos disponíveis
2. Se inscreve se registrando no sistema
3. Preenche os campos necessários

Tabelas:
1. users = Laravel users
2. processos = editais
3. inscrições = candidatos
4. questionarios = formulários dos processos
5. campos = todos os campos de cada formulário
6. respostas = todos os valores enviados dos campos de cada formulário

![ppgselecaoModel](https://user-images.githubusercontent.com/10613364/62972517-8f8ead00-bdea-11e9-8407-6af3b2c156fc.png)
